name: 0PT1MATES
title: 0pt1mates web site
org: 0PT1MATES
base_url: ''
profiles:
  development:
    base_url: 'http://localhost:4242/'
  production:
    base_url: 'http://0pt1mates.github.io'
    deploy:
      host: github_pages
      # use master branch for username.github.io repository
      branch: master
